# Generated by Django 4.0.4 on 2022-10-01 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todolist_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.date(2022, 9, 30)),
            preserve_default=False,
        ),
    ]
